### ISSUE TITLE
java.io.IOException: Cannot run program "dot"

### ISSUE THREAD

**Issue by dreamflyings** [freechipsproject/diagrammer#20]
[error] (run-main-0) java.io.IOException: Cannot run program "dot": error=2, No such file or directory
[error] java.io.IOException: Cannot run program "dot": error=2, No such file or directory
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
[error] iagrammeat scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:99)
[error]         at dotvisualizer.FirrtlDiagrammer$.render(FirrtlDiagrammer.scala:91)
[error]         at dotvisualizer.transforms.ModuleLevelDiagrammer.execute(ModuleLevelDiagrammer.scala:184)
[error]         at dotvisualizer.FirrtlDiagrammer$.run(FirrtlDiagrammer.scala:179)
[error]         at dotvisualizer.FirrtlDiagrammer$.main(FirrtlDiagrammer.scala:233)
[error]         at dotvisualizer.FirrtlDiagrammer.main(FirrtlDiagrammer.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error]         at java.lang.UNIXProcess.forkAndExec(Native Method)
[error]         at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[error]         at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:100)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:99)
[error]         at d

**Comment by chick** [comment]
You need to have the `dot` program installed. `dot` is part of [GraphViz](https://graphviz.gitlab.io/download/). This is mentioned in the README.
Sorry for the confusion.

**Comment by dreamflyings** [comment]
Thank you very much. The problem has been solved.
