### ISSUE TITLE
Type mismatch error in  ModuleLevelDiagrammer.scala and possible solution

### ISSUE THREAD

**Issue by ChengHongxu** [freechipsproject/diagrammer#5]
When I try the program (in the bash on Windows10), the following error occurs:

[error] /mnt/d/Projects/diagrammer/src/main/scala/dotvisualizer/transforms/ModuleLevelDiagrammer.scala:129: type mismatch;
[error]  found   : firrtl.ir.Statement => Unit
[error]  required: Unit => Unit
[error]           module map InstanceGraph.collectInstances(set)
[error]                                                    ^
[error] /mnt/d/Projects/diagrammer/src/main/scala/dotvisualizer/transforms/ModuleLevelDiagrammer.scala:129: No implicit view available from Unit => Unit => firrtl.Mappers.ModuleMagnet.
[error]           module map InstanceGraph.collectInstances(set)
[error]                  ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed

Then I did some research on Firrtl and changed the error line "module map InstanceGraph.collectInstances(set)" to "module foreachStmt InstanceGraph.collectInstances(set)", and now everything works well.

I post this issue as a reference for the author or someone else who gets the same error.

**Comment by chick** [comment]
Thanks for finding and diagnosing the problem.  PR #6 has been created it fix this issue. It will be distributed soon.

**Comment by edwardcwang** [comment]
Did #6 fix the problem? If not, please feel free to re-open this issue.
